"""added the userid in the taskmode

Revision ID: 11bebb8b0d57
Revises: 
Create Date: 2026-10-07 10:09:19.884821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11bebb8b0d57'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('user_tasks', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user_tasks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'user_tasks', 'user_table', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'user_tasks', type_='foreignkey')
    op.drop_column('user_tasks', 'updated_at')
    op.drop_column('user_tasks', 'created_at')
    op.drop_column('user_tasks', 'user_id')
    # ### end Alembic commands ###
